#+SETUPFILE: ./theme-readtheorg-local.setup
#+HTML_HEAD: <style> #content{max-width:100%;}</style>

#+TITLE: Exuanbo's Wiki
#+AUTHOR: Exuanbo

#+BEGIN_CENTER
This document is built using Emacs [[https://orgmode.org/][Org mode]] with the [[https://github.com/fniessen/org-html-themes][ReadTheOrg]] theme. I'm still learning and exploring this amazing tool.
#+END_CENTER

* Life
** Marathon
- 知乎圆桌[[https://www.zhihu.com/roundtable/marathon2015/][《马拉松之路》]]
- [[https://www.zhihu.com/question/21557037][有哪些配合马拉松训练的核心力量训练项目或计划？]]
  - 核心力量训练是指针对核心区域肌肉（主要是腹部、下背部和骨盆部肌群）及其深层小肌肉进行的力量、稳定、平衡等能力的训练，它不同于传统的腰腹力量训练，而是使核心区域的整体原动肌和局部稳定肌均能通过训练得到发展和提高。核心力量训练的目的就是使整个机体协调起来，确保训练者在做动作时核心肌群起到稳定躯体，传输能量的作用。
- [[http://thespiral.fm/episodes/4][Episode 004 — 当我们谈跑步时，我们谈些什么]]
- 动画[[https://movie.douban.com/subject/30238385/][《强风吹拂》]]
  - [[http://thespiral.fm/episodes/5][Episode 005 — 纵使强风起，人生不言弃]]

** IME
*** 双拼
- [[https://sspai.com/post/33019][选择输入法的哲学：兼论双拼的优缺点]]

*** RIME
**** Squirrel
- [[https://github.com/placeless/squirrel_config][placeless/squirrel_config]] - Rime 鼠须管小鹤双拼配置
- [[https://github.com/cnfeat/Rime][cnfeat/Rime]] - 鼠须管 小鹤双拼 输入法配置及配色方案

** Podcast
*** App
泛用型播客客户端：
- [[https://castro.fm/][Castro]] - iOS
- [[https://overcast.fm/][Overcast]] - iOS
- [[https://www.pocketcasts.com/][Pocket Casts]] - Android & iOS

*** Explore
- [[https://letter.getpodcast.xyz/][播客 Feed 订阅]]

*** Subscription
Favorites：
- [[https://teacherluke.co.uk/][Luke's English Podcast]]
- [[https://feeds.fireside.fm/casticle/rss][Casticle]]
- [[http://rss.lizhi.fm/rss/1959617.xml][得意忘形播客]]
- [[https://feeds.fireside.fm/bytecoffee/rss][Byte.Coffee]]
- [[https://czgx.fireside.fm/rss][迟早更新]]
- [[http://feed.tangsuanradio.com/gadio.xml][机核网 GADIO 游戏广播]]
- [[http://web.archive.org/web/20160604093615/http://antiwave.net/][反波 Antiwave - web.archive.org]]

完整 opml 格式订阅列表：[[./subscriptions.opml][subscriptions.opml]]

** Bypass GFW
- [[https://www.v2ray.com/][V2Ray]]
  - [[https://guide.v2fly.org/advanced/wss_and_web.html][WebSocket + TLS + Web]]
- [[https://github.com/trojan-gfw/trojan][trojan-gfw/trojan]]
- [[https://github.com/yichengchen/clashX/tree/master][ClashX]] - macOS
- [[https://apps.apple.com/us/app/shadowrocket/id932747118][Shadowroket]] - iOS
- [[https://github.com/Hackl0us/SS-Rule-Snippet][Hackl0us/SS-Rule-Snippet]] - Surge / Quantumult / Shadowrocket / Surfboard / clash(X) 实用规则

** Job
[[https://github.com/jwasham/coding-interview-university][jwasham/coding-interview-university]]

- [[https://github.com/greatghoul/remote-working][greatghoul/remote-working]] - 本列表只收录中国国内的资源或者对国内受众友好的国外资源
- [[https://www.zhihu.com/question/39610449][在谷歌日本(Google Japan)工作是怎样一番体验？ - 知乎]]
- [[https://www.zhihu.com/question/24099873][如何得到 Google 的工作机会？ - 知乎]]

* Language Learning
* Reading
** Blog
- [[http://www.yinwang.org/][当然我在扯淡 - 王垠]]
- [[https://blog.imalan.cn/][无文字 | 三无计划]]

* Game
** Development
- [[https://indienova.com/groups/14][我们都爱像素风 - Indienova 小组]]

* Programming
- [[https://opensource.guide/][Open Source Guides]]
- [[http://coolshell.cn/articles/4990.html][程序员技术练级攻略]]
  - [[https://exuanbo.xyz/posts/programmer/][2018 新版索引]]

* Web
* Git
** Commands
#+begin_src shell
git init  # 在当前目录新建一个 Git 代码库
git clone [url]  # 下载一个项目和它的整个代码历史
git config --list # 显示当前的 Git 配置
git config -e [--global]  # 编辑 Git 配置文件
git add  # 添加指定文件到暂存区
git rm   # 删除工作区文件，并且将这次删除放入暂存区
git commit -m [message]  # 提交暂存区到仓库区
git commit -a # 提交工作区自上次 commit 之后的变化，直接到仓库区
git commit --amend -m [message]   # 使用一次新的 commit，替代上一次提交 如果代码没有任何新变化，则用来改写上一次 commit 的提交信息
git commit --amend [file1] [file2] ...  # 重做上一次 commit，并包括指定文件的新变化

# 分支相关
git branch  # 列出所有本地分支
git branch -r  # 列出所有远程分支
git branch [branch-name]  # 新建一个分支，但依然停留在当前分支
git checkout [branch-name]  # 切换到指定分支，并更新工作区
git checkout -b [branch]  # 新建一个分支，并切换到该分支
git branch [branch] [commit]  # 新建一个分支，指向指定 commit
git checkout -b [branch] [tag]  # 新建一个分支，指向某个 tag
git branch --track [branch] [remote-branch]  # 新建一个分支，与指定的远程分支建立追踪关系
git branch --set-upstream [branch] [remote-branch]  # 建立追踪关系，在现有分支与指定的远程分支之间
git merge [branch]  # 合并指定分支到当前分支
git cherry-pick [commit]  # 选择一个 commit，合并进当前分支
git branch -d [branch-name]  # 删除分支
git push origin --delete [branch-name] # 删除远程分支
git branch -dr [remote/branch]  # 删除远程分支

# 标签
git tag  # 列出所有 tag
git tag [tag] # 新建一个 tag 在当前 commit
git tag [tag] [commit] # 新建一个 tag 在指定 commit
git show [tag]  # 查看 tag 信息
git push [remote] [tag]  # 提交指定 tag
git push [remote] --tags   # 提交所有 tag

# 查看
git status # 显示有变更的文件
git log # 显示当前分支的版本历史
git log --stat # 显示 commit 历史，以及每次 commit 发生变更的文件
git log --follow [file] # 显示某个文件的版本历史，包括文件改名
git log -p [file] # 显示指定文件相关的每一次 diff
git blame [file] # 显示指定文件是什么人在什么时间修改过
git diff # 显示暂存区和工作区的差异
git diff --cached [file] # 显示暂存区和上一个 commit 的差异
git diff HEAD # 显示工作区与当前分支最新 commit 之间的差异
git diff [first-branch]...[second-branch] # 显示两次提交之间的差异
git show [commit] # 显示某次提交的元数据和内容变化
git show --name-only [commit] # 显示某次提交发生变化的文件
git show [commit]:[filename] # 显示某次提交时，某个文件的内容
git reflog # 显示当前分支的最近几次提交

# 远程
git fetch [remote] # 下载远程仓库的所有变动
git remote -v  # 显示所有远程仓库
git remote show [remote]  # 显示某个远程仓库的信息
git remote add [shortname] [url]  # 增加一个新的远程仓库，并命名
git pull [remote] [branch]  # 取回远程仓库的变化，并与本地分支合并
git push [remote] [branch] # 上传本地指定分支到远程仓库
git push [remote] --force # 强行推送当前分支到远程仓库，即使有冲突
git push [remote] --all # 推送所有分支到远程仓库

# 撤销
git checkout [file] # 恢复暂存区的指定文件到工作区
git checkout [commit] [file] # 恢复某个 commit 的指定文件到工作区
git checkout . # 恢复上一个 commit 的所有文件到工作区
git reset [file] # 重置暂存区的指定文件，与上一次 commit 保持一致，但工作区不变
git reset --hard # 重置暂存区与工作区，与上一次 commit 保持一致
git reset [commit] # 重置当前分支的指针为指定 commit，同时重置暂存区，但工作区不变
git reset --hard [commit] # 重置当前分支的 HEAD 为指定 commit，同时重置暂存区和工作区，与指定 commit 一致
git reset --keep [commit] # 重置当前 HEAD 为指定 commit，但保持暂存区和工作区不变
git revert [commit] # 新建一个 commit，用来撤销指定 commit，后者的所有变化都将被前者抵消，并且应用到当前分支
#+end_src

** Pull-Request steps
[[http://akrabat.com/the-beginners-guide-to-contributing-to-a-github-project/][The beginner's guide to contributing to a GitHub project]]
1. Fork the project and clone locally
2. ~git remote add upstream git@github.com:xxx/xxx.git~
3. ~git checkout -b newBranch~
4. Do something and commit
5. ~git pull --rebase upstream master~
6. ~git push origin~

** Github Pages
- [[https://stackoverflow.com/questions/11577147/how-to-fix-http-404-on-github-pages][How to fix HTTP 404 on Github Pages?]] If you don't use Jekyll, the workaround is to place a file named ~.nojekyll~ in the root directory.

* Text Editor
** Emacs
- [[https://github.com/redguardtoo/mastering-emacs-in-one-year-guide/blob/master/guide-zh.org][mastering-emacs-in-one-year-guide/guide-zh.org at master · redguardtoo/mastering-emacs-in-one-year-guide]]
- [[http://planet.emacsen.org/][Planet Emacsen]]

** Spacemacs
[[https://github.com/syl20bnr/spacemacs][spacemacs]] 是一款社区维护的 Emacs 配置，结合了 vim 和 Emacs 两者的优点。

*** Shortcuts
#+begin_example
C-h f & C-h C-f : Find Function definition
C-h v & C-h C-v : Find variable definition
SPC s l : Navigation functions in current file
SPC f e d : Go to your .spacemacs file
SPC f e i : Go to .emacs.d/init.el
SPC h L : Find an elpa library
SPC f e h : Find Spacemacs layers, docs and package configuration

SPC b b & SPC b B(i) : show all opened buffer
SPC b h : Open spacemacs home buffer
SPC b s : Open scratch buffer
SPC b f : Reveal in finder
SPC b w : Read only mode.
SPC b n/p : previous or next buffer
SPC b TAB : to switch back and forth.

SPC f f : helm find file
SPC f r : open recent file
SPC f R : rename file
SPC f c : copy file
SPC f j : jump to dired
SPC f t : open neo tree
SPC f o : open in external application

SPC p f / SPC p b : open project file or buffer
SPC p t : open project neotree

SPC l o : custom layout
SPC l L/s : load or save layout
SPC l l : switch bewteen layout
SPC l TAB : quick way to switch
SPC l ? : open up the help.
SPC p l : switch to project and create a layout
#+end_example

* Org Mode
- [[http://doc.norang.ca/org-mode.html][Org Mode - Organize Your Life In Plain Text!]]
- 使用主题自带代码高亮方案 ~(org :variables org-html-htmlize-output-type 'css)~

* Chrome
* OS
** Linux
** MacOS
- [[https://github.com/jaywcjlove/awesome-mac][jaywcjlove/awesome-mac]]
- [[https://github.com/robbyrussell/oh-my-zsh][oh-my-zsh]]
- [[http://brew.sh/][Homebrew]]
  - [[https://github.com/phinze/homebrew-cask][homebrew-cask]]
  - ~brew leavese~ Show installed formulae that are not dependencies of another installed formula
  - [[https://github.com/beeftornado/homebrew-rmtree][beeftornado/homebrew-rmtree]] - Remove a formula and its unused dependencies
- [[https://github.com/gnachman/iTerm2][iTerm2]]
- [[http://www.alfredapp.com/][Alfred]]
  - [[http://www.alfredworkflow.com/][alfredworkflow]]

*** Setup
- [[http://sourabhbajaj.com/mac-setup/index.html][Mac OS X Setup Guide]]
- 改变 Launchpad 中应用图标的大小
   #+begin_src shell
   defaults write com.apple.dock springboard-columns -int 列数
   defaults write com.apple.dock springboard-rows -int 行数
   defaults write com.apple.dock ResetLaunchPad -bool TRUE
   killall Dock
   #+end_src

** Windows
* Database
* Algorithm
* Design
* Latex
